### ISSUE TITLE
Doesn't install with 2.0.1

### ISSUE THREAD

**Issue by jarthod** [abl/pTOTP#3]
Hi,

I just updated my pebble app and watch to 2.0.1 and I can't install my generated authenticator any more. I saw a pull request about SDK 2.0 compatibility though, Is it a known problem ? is there anything I can do ? are you using 2.0 ?

When I open the app on my phone (android) it launches the pebble app and tells "this app is untrusted, are you sure ?", I say yes and it goes to the pebble home screen with no changes. The app is nowhere to be found.

I tried both alternatives on the pebble store by they are all crappy, the first need 3 reset before working, and silently delete tokens it don't like (half of mine), and the other one is slow and limits name to 6 chars.

**Comment by Azenet** [comment]
Having the same issue. I think that, even though the pull request was merged, the app wasn't updated on the gh-pages.

**Comment by abl** [comment]
Hey, sorry about the trouble.

Unfortunately I changed companies a few months ago and one of the contract terms prevents me from working on this project without approval (which I haven't been able to get.)

I was hoping someone would've improved on this (and some have!) but it looks like nothing has made it to the app store (and honestly, I don't like the idea of some of the solutions I've seen...lots of potential data leakage.)

Have you tried @TrueJournals' fork?

**Comment by Azenet** [comment]
@abl Aw, that's unfortunate.
I just tried his fork, and it seems to work fine so far! It might easily be guessed, but for anyone looking for it, the github pages with the generator is [here](http://truejournals.github.io/pTOTP/).

**Comment by jarthod** [comment]
@TrueJournals fork is working perfectly ;)

**Comment by abl** [comment]
Resolving; glad it worked!
